// <auto-generated />
using System;
using HappyVacation.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HappyVacation.Database.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20220412132557_UpdateOrderTable")]
    partial class UpdateOrderTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HappyVacation.Database.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "adventure tour"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "artistic tour"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "beach tour"
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "biking tour"
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "boating tour"
                        },
                        new
                        {
                            Id = 6,
                            CategoryName = "camping"
                        },
                        new
                        {
                            Id = 7,
                            CategoryName = "classic tour"
                        },
                        new
                        {
                            Id = 8,
                            CategoryName = "cooking tour"
                        },
                        new
                        {
                            Id = 9,
                            CategoryName = "craft tour"
                        },
                        new
                        {
                            Id = 10,
                            CategoryName = "cruises tour"
                        },
                        new
                        {
                            Id = 11,
                            CategoryName = "culinary tour"
                        },
                        new
                        {
                            Id = 12,
                            CategoryName = "cultural tour"
                        },
                        new
                        {
                            Id = 13,
                            CategoryName = "discovery tour"
                        },
                        new
                        {
                            Id = 14,
                            CategoryName = "fishing tour"
                        },
                        new
                        {
                            Id = 15,
                            CategoryName = "heritage tour"
                        },
                        new
                        {
                            Id = 16,
                            CategoryName = "historical tour"
                        },
                        new
                        {
                            Id = 17,
                            CategoryName = "homestay tour"
                        },
                        new
                        {
                            Id = 18,
                            CategoryName = "honeymoon  tour"
                        },
                        new
                        {
                            Id = 19,
                            CategoryName = "luxury tour"
                        },
                        new
                        {
                            Id = 20,
                            CategoryName = "'motorcycle  tour"
                        },
                        new
                        {
                            Id = 21,
                            CategoryName = "nature-based tour"
                        },
                        new
                        {
                            Id = 23,
                            CategoryName = "relaxing tour"
                        },
                        new
                        {
                            Id = 24,
                            CategoryName = "shopping tour"
                        },
                        new
                        {
                            Id = 25,
                            CategoryName = "snorkeling tour"
                        },
                        new
                        {
                            Id = 26,
                            CategoryName = "sports tour"
                        },
                        new
                        {
                            Id = 27,
                            CategoryName = "trekking  tour"
                        },
                        new
                        {
                            Id = 28,
                            CategoryName = "walking  tour"
                        });
                });

            modelBuilder.Entity("HappyVacation.Database.Entities.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsIncluded")
                        .HasColumnType("bit");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TourId");

                    b.ToTable("Expenses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Hotel pickup and drop-off in Hoi An City Center",
                            IsIncluded = true,
                            TourId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "Transportation with air-conditioning",
                            IsIncluded = true,
                            TourId = 1
                        },
                        new
                        {
                            Id = 3,
                            Content = "Bicycle",
                            IsIncluded = true,
                            TourId = 1
                        },
                        new
                        {
                            Id = 4,
                            Content = "Entrance fees",
                            IsIncluded = true,
                            TourId = 1
                        },
                        new
                        {
                            Id = 5,
                            Content = "Foods and Bottled drinking water",
                            IsIncluded = true,
                            TourId = 1
                        },
                        new
                        {
                            Id = 6,
                            Content = "Tips and gratuities",
                            IsIncluded = false,
                            TourId = 1
                        },
                        new
                        {
                            Id = 7,
                            Content = "Personal expenses such as: shopping, telephone, beverage, etc.",
                            IsIncluded = false,
                            TourId = 1
                        },
                        new
                        {
                            Id = 8,
                            Content = "Hotel pickup and drop-off in Hoi An City Center",
                            IsIncluded = true,
                            TourId = 2
                        },
                        new
                        {
                            Id = 9,
                            Content = "Transportation with air-conditioning",
                            IsIncluded = true,
                            TourId = 2
                        },
                        new
                        {
                            Id = 10,
                            Content = "Boat",
                            IsIncluded = true,
                            TourId = 2
                        },
                        new
                        {
                            Id = 11,
                            Content = "Entrance fees",
                            IsIncluded = true,
                            TourId = 2
                        },
                        new
                        {
                            Id = 12,
                            Content = "Dinner",
                            IsIncluded = true,
                            TourId = 2
                        },
                        new
                        {
                            Id = 13,
                            Content = "English-speaking tour guide",
                            IsIncluded = true,
                            TourId = 2
                        },
                        new
                        {
                            Id = 14,
                            Content = "Tips and gratuities",
                            IsIncluded = false,
                            TourId = 2
                        },
                        new
                        {
                            Id = 15,
                            Content = "Personal expenses such as: shopping, telephone, beverage, etc.",
                            IsIncluded = false,
                            TourId = 2
                        });
                });

            modelBuilder.Entity("HappyVacation.Database.Entities.Itinerary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TourId");

                    b.ToTable("Itineraries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Discover Hoi An’s countryside and its local foods by bicycle. Local foods in Hoi An are known and enjoyed by the tourists once setting foot here. In Hoi An, these cuisines are very popular and sold everywhere in all streets. Moreover, these cuisines are considered as unique symbols for the culture and introduced to every tourist. We bike through the countryside to a Tra Que Village.",
                            Title = "Part 1",
                            TourId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "Vegetables from this village are distributed to most of the restaurants in town and specially make the Cao Lau to have a perfect taste. Go back to town and learn how to make special “white rose” dumpling cakes with a local family and taste your products.",
                            Title = "Part 2",
                            TourId = 1
                        },
                        new
                        {
                            Id = 3,
                            Content = "Continue riding to Cam Nam to enjoy the Yin and Yang food such as: Banh Dap (“cracked or smashed rice pancake”), Che Bap (“corn and coconut sweet soup”). We then ride to a famous local restaurant for Hoi An specialty - Cao Lau. Cao Lau is a traditional Hoi An specialty composed of local noodles, pork, fresh vegetables and rice paper.",
                            Title = "Part 3",
                            TourId = 1
                        },
                        new
                        {
                            Id = 4,
                            Content = "We will ride back to the company at the end of our trip.",
                            Title = "Part 4",
                            TourId = 1
                        },
                        new
                        {
                            Id = 5,
                            Content = "We will visit the Japanese Covered Bridge - one of Vietnam's most iconic attraction and a beautiful historical piece of Japanese architecture. Walking in the ancient streets at night, you can perceive the ancient beauty of Hoi An City.",
                            Title = "Part 1",
                            TourId = 2
                        },
                        new
                        {
                            Id = 6,
                            Content = "We will visit one of Hoi An Museums and an Ancient House which boast a remarkable architectural style and rest under the glistening lantern lights.",
                            Title = "Part 2",
                            TourId = 2
                        },
                        new
                        {
                            Id = 7,
                            Content = "Enjoy Bai Choi performance by the bank of Hoai river. Bai Choi combines music, poetry, acting, painting and literature, has been recognized by UNESCO as an intangible heritage of humanity.",
                            Title = "Part 3",
                            TourId = 2
                        },
                        new
                        {
                            Id = 8,
                            Content = "Have dinner at a restaurant with romantic river view then ake a 15-minute boat trip on Hoai River lighting and floating your own candle lit coloured paper lantern on the river with wishes and go shopping at Hoi An night market.",
                            Title = "Part 4",
                            TourId = 2
                        });
                });

            modelBuilder.Entity("HappyVacation.Database.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Adults")
                        .HasColumnType("int");

                    b.Property<string>("CancelReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Children")
                        .HasColumnType("int");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProviderId")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.Property<string>("TouristEmail")
                        .IsRequired()
                        .HasMaxLength(62)
                        .HasColumnType("nvarchar(62)");

                    b.Property<string>("TouristName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("TouristPhone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.HasIndex("TourId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adults = 2,
                            Children = 1,
                            DepartureDate = new DateTime(2022, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderDate = new DateTime(2022, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProviderId = 1,
                            State = "Confirmed",
                            TourId = 1,
                            TouristEmail = "braddinh1952000@gmail.com",
                            TouristName = "Dinh Cong Tai",
                            TouristPhone = "0945501905",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Adults = 2,
                            Children = 0,
                            DepartureDate = new DateTime(2022, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderDate = new DateTime(2022, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProviderId = 1,
                            State = "Confirmed",
                            TourId = 2,
                            TouristEmail = "braddinh1952000@gmail.com",
                            TouristName = "Dinh Cong Tai",
                            TouristPhone = "0945501905",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("HappyVacation.Database.Entities.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsTop")
                        .HasColumnType("bit");

                    b.Property<string>("PlaceName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Places", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsTop = true,
                            PlaceName = "Da Nang",
                            ThumbnailUrl = "/storage/danang.jpg"
                        },
                        new
                        {
                            Id = 2,
                            IsTop = true,
                            PlaceName = "Hue",
                            ThumbnailUrl = "/storage/hue.jpg"
                        },
                        new
                        {
                            Id = 3,
                            IsTop = true,
                            PlaceName = "Hoi An",
                            ThumbnailUrl = "/storage/hoian.jpg"
                        },
                        new
                        {
                            Id = 4,
                            IsTop = false,
                            PlaceName = "Ha Long",
                            ThumbnailUrl = "/storage/halong.jpg"
                        },
                        new
                        {
                            Id = 5,
                            IsTop = true,
                            PlaceName = "Ha Noi",
                            ThumbnailUrl = "/storage/hanoi.jpg"
                        },
                        new
                        {
                            Id = 6,
                            IsTop = true,
                            PlaceName = "Ho Chi Minh",
                            ThumbnailUrl = "/storage/hochiminh.jpg"
                        },
                        new
                        {
                            Id = 7,
                            IsTop = false,
                            PlaceName = "Da Lat",
                            ThumbnailUrl = "/storage/dalat.jpg"
                        },
                        new
                        {
                            Id = 8,
                            IsTop = true,
                            PlaceName = "Nha Trang",
                            ThumbnailUrl = "/storage/nhatrang.jpg"
                        },
                        new
                        {
                            Id = 9,
                            IsTop = false,
                            PlaceName = "Phu Quoc",
                            ThumbnailUrl = "/storage/phuquoc.jpg"
                        },
                        new
                        {
                            Id = 10,
                            IsTop = false,
                            PlaceName = "Quy Nhon",
                            ThumbnailUrl = "/storage/quynhon.jpg"
                        },
                        new
                        {
                            Id = 11,
                            IsTop = false,
                            PlaceName = "Sa Pa",
                            ThumbnailUrl = "/storage/sapa.jpg"
                        },
                        new
                        {
                            Id = 12,
                            IsTop = false,
                            PlaceName = "Vung Tau",
                            ThumbnailUrl = "/storage/vungtau.jpg"
                        },
                        new
                        {
                            Id = 13,
                            IsTop = false,
                            PlaceName = "Mui Ne",
                            ThumbnailUrl = "/storage/muine.jpg"
                        },
                        new
                        {
                            Id = 14,
                            IsTop = false,
                            PlaceName = "Con Dao",
                            ThumbnailUrl = "/storage/condao.jpg"
                        },
                        new
                        {
                            Id = 15,
                            IsTop = false,
                            PlaceName = "Trang An",
                            ThumbnailUrl = "/storage/trangan.jpg"
                        });
                });

            modelBuilder.Entity("HappyVacation.Database.Entities.Provider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("ProviderEmail")
                        .IsRequired()
                        .HasMaxLength(62)
                        .HasColumnType("nvarchar(62)");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProviderPhone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Providers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "32 Tien Giang St, Tan Binh District, Ho Chi Minh City, Viet Nam",
                            AvatarUrl = "/storage/hoianexpresslogo.jpg",
                            DateCreated = new DateTime(2022, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Established in 2002, Hoi An Express is a company specializing in organizing professional tours for foreign visitors to Vietnam to visit tours, conferences, events combined with team building.",
                            IsEnabled = true,
                            ProviderEmail = "info@hoianexpress.com.vn",
                            ProviderName = "Hoi An Express",
                            ProviderPhone = "0905123456"
                        });
                });

            modelBuilder.Entity("HappyVacation.Database.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TourId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "This is a good tour! A lot of interesting experiences.",
                            DateCreated = new DateTime(2022, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(2022, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4f,
                            TourId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "I love it! Had a really relaxing time.",
                            DateCreated = new DateTime(2022, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(2022, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4f,
                            TourId = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("HappyVacation.Database.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "Provider"
                        },
                        new
                        {
                            Id = 3,
                            RoleName = "Tourist"
                        });
                });

            modelBuilder.Entity("HappyVacation.Database.Entities.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float>("Duration")
                        .HasColumnType("real");

                    b.Property<int>("GroupSize")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MinAdults")
                        .HasColumnType("int");

                    b.Property<string>("Overview")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PricePerAdult")
                        .HasColumnType("int");

                    b.Property<int>("PricePerChild")
                        .HasColumnType("int");

                    b.Property<int>("ProviderId")
                        .HasColumnType("int");

                    b.Property<string>("TourName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.ToTable("Tours", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Destination = "Cam Chau Ward, Hoi An City, Quang Nam Province",
                            Duration = 0.5f,
                            GroupSize = 15,
                            IsAvailable = true,
                            IsPrivate = false,
                            Location = "Minh An Ward, Hoi An City, Quang Nam Province",
                            MinAdults = 2,
                            Overview = "Take a journey through Hoi An’s culinary history; head out to the beautiful countryside by bicycle to experience some traditional local food favorites, including the most famous of Hoi An specialties; Cao Lau. Try the traditional Hoi An specialty, Cao Lau; intoxicating pork noodle broth, featuring sticky rice noodles that must be soaked in water from the oldest well in Hoi An, Ba Le Well.",
                            PricePerAdult = 89,
                            PricePerChild = 30,
                            ProviderId = 1,
                            TourName = "HALF-DAY FOODIE TOUR BY BICYCLE & VISIT TRA QUE VEGETABLE VILLAGE",
                            ViewCount = 10
                        },
                        new
                        {
                            Id = 2,
                            Destination = "Minh An Ward, Hoi An City, Quang Nam Province",
                            Duration = 0.125f,
                            GroupSize = 15,
                            IsAvailable = true,
                            IsPrivate = true,
                            Location = "Minh An Ward, Hoi An City, Quang Nam Province",
                            MinAdults = 1,
                            Overview = "Have a memorable end to your day in Hoi An with a tour of the ancient town after the sun goes down. See the centuries-old houses and monuments illuminated by local lanterns. Visit a traditional restaurant for dinner",
                            PricePerAdult = 180,
                            PricePerChild = 50,
                            ProviderId = 1,
                            TourName = "Private Tour: HOI AN MYSTERIOUS NIGHT TOUR WITH DINNER FROM HOI AN",
                            ViewCount = 5
                        });
                });

            modelBuilder.Entity("HappyVacation.Database.Entities.TourCategory", b =>
                {
                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("TourId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("TourCategories", (string)null);

                    b.HasData(
                        new
                        {
                            TourId = 1,
                            CategoryId = 4
                        },
                        new
                        {
                            TourId = 1,
                            CategoryId = 7
                        },
                        new
                        {
                            TourId = 1,
                            CategoryId = 8
                        },
                        new
                        {
                            TourId = 1,
                            CategoryId = 11
                        },
                        new
                        {
                            TourId = 2,
                            CategoryId = 11
                        },
                        new
                        {
                            TourId = 2,
                            CategoryId = 12
                        });
                });

            modelBuilder.Entity("HappyVacation.Database.Entities.TourImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TourId");

                    b.ToTable("TourImages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TourId = 1,
                            Url = "/storage/tour11.jpg"
                        },
                        new
                        {
                            Id = 2,
                            TourId = 1,
                            Url = "/storage/tour12.jpg"
                        },
                        new
                        {
                            Id = 3,
                            TourId = 1,
                            Url = "/storage/tour13.jpg"
                        },
                        new
                        {
                            Id = 4,
                            TourId = 1,
                            Url = "/storage/tour14.jpg"
                        },
                        new
                        {
                            Id = 5,
                            TourId = 2,
                            Url = "/storage/tour21.jpg"
                        },
                        new
                        {
                            Id = 6,
                            TourId = 2,
                            Url = "/storage/tour22.jpg"
                        },
                        new
                        {
                            Id = 7,
                            TourId = 2,
                            Url = "/storage/tour23.jpg"
                        },
                        new
                        {
                            Id = 8,
                            TourId = 2,
                            Url = "/storage/tour24.jpg"
                        });
                });

            modelBuilder.Entity("HappyVacation.Database.Entities.TourPlace", b =>
                {
                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.Property<int>("PlaceId")
                        .HasColumnType("int");

                    b.HasKey("TourId", "PlaceId");

                    b.HasIndex("PlaceId");

                    b.ToTable("TourPlaces", (string)null);

                    b.HasData(
                        new
                        {
                            TourId = 1,
                            PlaceId = 3
                        },
                        new
                        {
                            TourId = 2,
                            PlaceId = 3
                        });
                });

            modelBuilder.Entity("HappyVacation.Database.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(62)
                        .HasColumnType("nvarchar(62)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("ProviderId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId")
                        .IsUnique()
                        .HasFilter("[ProviderId] IS NOT NULL");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ngoluuquocdat@gmail.com",
                            FirstName = "Quoc Dat",
                            IsEnabled = true,
                            LastName = "Ngo Luu",
                            PasswordHash = new byte[] { 78, 156, 226, 239, 122, 162, 172, 126, 103, 194, 91, 164, 93, 216, 58, 150, 211, 88, 223, 3, 150, 84, 254, 136, 233, 70, 192, 68, 172, 186, 66, 176, 43, 4, 190, 30, 97, 228, 233, 154, 75, 178, 236, 205, 223, 116, 41, 136, 44, 166, 226, 168, 37, 234, 68, 70, 211, 215, 167, 3, 247, 34, 230, 246 },
                            PasswordSalt = new byte[] { 211, 76, 32, 105, 37, 143, 186, 238, 133, 227, 196, 70, 72, 172, 102, 220, 200, 241, 208, 65, 227, 196, 32, 66, 26, 23, 231, 131, 25, 113, 190, 157, 253, 179, 95, 81, 234, 189, 159, 121, 244, 29, 18, 147, 84, 105, 190, 140, 160, 96, 22, 53, 39, 91, 207, 118, 126, 161, 50, 148, 186, 12, 189, 8, 223, 167, 29, 244, 220, 71, 82, 157, 109, 164, 214, 186, 174, 85, 164, 81, 22, 205, 81, 21, 249, 235, 235, 180, 131, 183, 144, 163, 103, 157, 190, 22, 74, 49, 123, 15, 126, 207, 253, 73, 186, 83, 7, 237, 185, 226, 247, 213, 105, 32, 213, 10, 246, 120, 108, 214, 82, 35, 74, 136, 172, 231, 178, 218 },
                            Phone = "0905553859",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            AvatarUrl = "/storage/tuan.jpg",
                            Email = "tuandang29042000@gmail.com",
                            FirstName = "Quoc Tuan",
                            IsEnabled = true,
                            LastName = "Dang",
                            PasswordHash = new byte[] { 104, 68, 191, 211, 220, 209, 96, 254, 86, 191, 4, 109, 163, 68, 230, 172, 142, 47, 53, 29, 69, 159, 95, 141, 219, 221, 108, 215, 14, 228, 198, 215, 176, 125, 4, 156, 196, 63, 92, 155, 57, 98, 116, 81, 136, 166, 20, 50, 126, 123, 44, 38, 101, 92, 241, 38, 43, 96, 37, 15, 105, 60, 91, 133 },
                            PasswordSalt = new byte[] { 211, 76, 32, 105, 37, 143, 186, 238, 133, 227, 196, 70, 72, 172, 102, 220, 200, 241, 208, 65, 227, 196, 32, 66, 26, 23, 231, 131, 25, 113, 190, 157, 253, 179, 95, 81, 234, 189, 159, 121, 244, 29, 18, 147, 84, 105, 190, 140, 160, 96, 22, 53, 39, 91, 207, 118, 126, 161, 50, 148, 186, 12, 189, 8, 223, 167, 29, 244, 220, 71, 82, 157, 109, 164, 214, 186, 174, 85, 164, 81, 22, 205, 81, 21, 249, 235, 235, 180, 131, 183, 144, 163, 103, 157, 190, 22, 74, 49, 123, 15, 126, 207, 253, 73, 186, 83, 7, 237, 185, 226, 247, 213, 105, 32, 213, 10, 246, 120, 108, 214, 82, 35, 74, 136, 172, 231, 178, 218 },
                            Phone = "0921231220",
                            ProviderId = 1,
                            Username = "quoctuan"
                        },
                        new
                        {
                            Id = 3,
                            AvatarUrl = "/storage/tai.jpg",
                            Email = "braddinh1952000@gmail.com",
                            FirstName = "Cong Tai",
                            IsEnabled = true,
                            LastName = "Dinh",
                            PasswordHash = new byte[] { 103, 226, 88, 123, 75, 46, 238, 177, 152, 63, 88, 138, 235, 109, 27, 21, 121, 12, 36, 193, 172, 65, 84, 236, 36, 247, 116, 53, 96, 129, 69, 190, 120, 51, 241, 228, 183, 124, 202, 102, 194, 205, 228, 38, 105, 56, 162, 118, 62, 251, 16, 138, 145, 174, 234, 204, 214, 85, 55, 109, 218, 184, 150, 223 },
                            PasswordSalt = new byte[] { 211, 76, 32, 105, 37, 143, 186, 238, 133, 227, 196, 70, 72, 172, 102, 220, 200, 241, 208, 65, 227, 196, 32, 66, 26, 23, 231, 131, 25, 113, 190, 157, 253, 179, 95, 81, 234, 189, 159, 121, 244, 29, 18, 147, 84, 105, 190, 140, 160, 96, 22, 53, 39, 91, 207, 118, 126, 161, 50, 148, 186, 12, 189, 8, 223, 167, 29, 244, 220, 71, 82, 157, 109, 164, 214, 186, 174, 85, 164, 81, 22, 205, 81, 21, 249, 235, 235, 180, 131, 183, 144, 163, 103, 157, 190, 22, 74, 49, 123, 15, 126, 207, 253, 73, 186, 83, 7, 237, 185, 226, 247, 213, 105, 32, 213, 10, 246, 120, 108, 214, 82, 35, 74, 136, 172, 231, 178, 218 },
                            Phone = "0945501905",
                            Username = "congtai"
                        },
                        new
                        {
                            Id = 4,
                            AvatarUrl = "/storage/dat.jpg",
                            Email = "ngoluuquocdat@gmail.com",
                            FirstName = "Quoc Dat",
                            IsEnabled = true,
                            LastName = "Ngo Luu",
                            PasswordHash = new byte[] { 25, 38, 41, 198, 188, 117, 211, 218, 44, 197, 114, 147, 69, 134, 241, 8, 251, 211, 48, 165, 25, 197, 203, 124, 72, 80, 12, 201, 56, 33, 120, 53, 51, 133, 184, 122, 30, 30, 38, 197, 35, 91, 16, 128, 89, 201, 190, 65, 229, 140, 4, 193, 45, 31, 24, 225, 74, 151, 209, 168, 59, 234, 182, 142 },
                            PasswordSalt = new byte[] { 211, 76, 32, 105, 37, 143, 186, 238, 133, 227, 196, 70, 72, 172, 102, 220, 200, 241, 208, 65, 227, 196, 32, 66, 26, 23, 231, 131, 25, 113, 190, 157, 253, 179, 95, 81, 234, 189, 159, 121, 244, 29, 18, 147, 84, 105, 190, 140, 160, 96, 22, 53, 39, 91, 207, 118, 126, 161, 50, 148, 186, 12, 189, 8, 223, 167, 29, 244, 220, 71, 82, 157, 109, 164, 214, 186, 174, 85, 164, 81, 22, 205, 81, 21, 249, 235, 235, 180, 131, 183, 144, 163, 103, 157, 190, 22, 74, 49, 123, 15, 126, 207, 253, 73, 186, 83, 7, 237, 185, 226, 247, 213, 105, 32, 213, 10, 246, 120, 108, 214, 82, 35, 74, 136, 172, 231, 178, 218 },
                            Phone = "0905553859",
                            Username = "quocdat"
                        });
                });

            modelBuilder.Entity("HappyVacation.Database.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("HappyVacation.Database.Entities.Expense", b =>
                {
                    b.HasOne("HappyVacation.Database.Entities.Tour", "Tour")
                        .WithMany("Expenses")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("HappyVacation.Database.Entities.Itinerary", b =>
                {
                    b.HasOne("HappyVacation.Database.Entities.Tour", "Tour")
                        .WithMany("Itineraries")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("HappyVacation.Database.Entities.Order", b =>
                {
                    b.HasOne("HappyVacation.Database.Entities.Provider", "Provider")
                        .WithMany("Orders")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HappyVacation.Database.Entities.Tour", "Tour")
                        .WithMany("Orders")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HappyVacation.Database.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Provider");

                    b.Navigation("Tour");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HappyVacation.Database.Entities.Review", b =>
                {
                    b.HasOne("HappyVacation.Database.Entities.Tour", "Tour")
                        .WithMany("Reviews")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HappyVacation.Database.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Tour");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HappyVacation.Database.Entities.Tour", b =>
                {
                    b.HasOne("HappyVacation.Database.Entities.Provider", "Provider")
                        .WithMany("Tours")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("HappyVacation.Database.Entities.TourCategory", b =>
                {
                    b.HasOne("HappyVacation.Database.Entities.Category", "Category")
                        .WithMany("TourCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HappyVacation.Database.Entities.Tour", "Tour")
                        .WithMany("TourCategories")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("HappyVacation.Database.Entities.TourImage", b =>
                {
                    b.HasOne("HappyVacation.Database.Entities.Tour", "Tour")
                        .WithMany("TourImages")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("HappyVacation.Database.Entities.TourPlace", b =>
                {
                    b.HasOne("HappyVacation.Database.Entities.Place", "Place")
                        .WithMany("TourPlaces")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HappyVacation.Database.Entities.Tour", "Tour")
                        .WithMany("TourPlaces")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("HappyVacation.Database.Entities.User", b =>
                {
                    b.HasOne("HappyVacation.Database.Entities.Provider", "Provider")
                        .WithOne("User")
                        .HasForeignKey("HappyVacation.Database.Entities.User", "ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("HappyVacation.Database.Entities.UserRole", b =>
                {
                    b.HasOne("HappyVacation.Database.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HappyVacation.Database.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HappyVacation.Database.Entities.Category", b =>
                {
                    b.Navigation("TourCategories");
                });

            modelBuilder.Entity("HappyVacation.Database.Entities.Place", b =>
                {
                    b.Navigation("TourPlaces");
                });

            modelBuilder.Entity("HappyVacation.Database.Entities.Provider", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Tours");

                    b.Navigation("User")
                        .IsRequired();
                });

            modelBuilder.Entity("HappyVacation.Database.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("HappyVacation.Database.Entities.Tour", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("Itineraries");

                    b.Navigation("Orders");

                    b.Navigation("Reviews");

                    b.Navigation("TourCategories");

                    b.Navigation("TourImages");

                    b.Navigation("TourPlaces");
                });

            modelBuilder.Entity("HappyVacation.Database.Entities.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Reviews");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
